# Generated by Django 4.1.4 on 2022-12-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyTab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paypal',
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendlyTab.user')),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('amount', models.CharField(max_length=15)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='friendlyTab.user')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='friendlyTab.user')),
            ],
        ),
    ]
